### PR TITLE
Merge toml-rs crate into the toml_edit repo

### PR DESCRIPTION
**Pull request by epage**
See https://github.com/alexcrichton/toml-rs/issues/460

### CODE REVIEW

**Comment by ordian** [comment]
@epage jFYI, I've created toml-rs org and transfered the repo here

**Comment by epage** [comment]
> FYI, I've created toml-rs org and transfered the repo here

Thanks!  I was going to look into where this should live, whether a toml-rs or in rust-lang

**Comment by epage** [comment]
@ordian will squash or rebase do the right thing with this or should we enable merge commits?

**Comment by ordian** [comment]
> @ordian will squash or rebase do the right thing with this or should we enable merge commits?

enabled merge commits

**Pull request merged**
